# Generated by Django 5.2.6 on 2025-09-26 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="config_schema",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="request_schema",
        ),
    ]
