# Generated by Django 5.2.6 on 2025-09-26 23:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("api_expires_on", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict, help_text="Key-value SDK parameters")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="configuration.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="templates",
            field=models.ManyToManyField(blank=True, related_name="services", to="configuration.template"),
        ),
    ]
