# Generated by Django 5.2.6 on 2025-09-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0005_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="templates",
        ),
        migrations.AddField(
            model_name="template",
            name="service",
            field=models.ForeignKey(
                to="configuration.service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                null=True,
                blank=True,
            ),
        ),
    ]
