# See https://pre-commit.com for more information
# Install hooks: poetry run pre-commit install
# To also run on push: poetry run pre-commit install -t pre-push

minimum_pre_commit_version: '3.6.0'

default_install_hook_types: [pre-commit]

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  # Ruff: Linter and Import sorter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
