# Generated by Django 5.2.6 on 2025-09-26 21:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="Provider code maps to a module under provider/{code}.py, e.g., "
                        '"PROVIDER NAME" -> "provider_name.py" or "providername.py".',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push Notification")], max_length=20
                    ),
                ),
                ("config_schema", models.JSONField(blank=True, default=dict)),
                ("request_schema", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "providers",
                "ordering": ["name"],
            },
        ),
    ]
