# Generated by Django 5.2.6 on 2025-09-26 22:27

from django.db import migrations


def create_mailgun_provider(apps, schema_editor):
    Provider = apps.get_model("notification", "Provider")
    # Ensure id is auto-generated (UUIDField default)
    Provider.objects.get_or_create(
        code="mailgun",
        defaults={"name": "Mailgun", "type": "email"},
    )


def remove_mailgun_provider(apps, schema_editor):
    Provider = apps.get_model("notification", "Provider")
    Provider.objects.filter(code="mailgun").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_remove_provider_config_schema_and_more"),
    ]

    operations = [
        migrations.RunPython(create_mailgun_provider, remove_mailgun_provider),
    ]
