# Generated by Django 5.2.6 on 2025-09-26 22:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_auto_20250926_2227"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("template", models.TextField(help_text="Message body with placeholders like {{ variable }}")),
                ("variables", models.JSONField(blank=True, default=list, editable=False)),
                ("version", models.IntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "db_table": "templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
