# Generated by Django 5.2.6 on 2025-09-27 00:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0006_alter_template_add_service_and_remove_service_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push Notification")],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "payload_config",
                    models.JSONField(blank=True, default=dict, help_text="Destination config like email/phone"),
                ),
                (
                    "content",
                    models.CharField(choices=[("html", "HTML"), ("text", "Text")], default="text", max_length=10),
                ),
                ("plain_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "PENDING"), ("sent", "SENT"), ("error", "Error")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("http_status", models.CharField(blank=True, max_length=50)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="configuration.service",
                    ),
                ),
                (
                    "template_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="configuration.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
