# Generated by Django 5.2.6 on 2025-09-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
